import Head from "next/head"
import MainContent from "@/views/MainContent"

export default function Home() {
    return (
        <>
            <Head>
                <title>Teste FrontEnd - Alexandre</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainContent />
        </>
    )
}
